version: 2.1
jobs:
  test:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-packages-v1-{{ .Branch }}-
            - yarn-packages-v1-
      - run: yarn install --freeze-lockfile
      - save_cache:
          paths:
            - ~/.cache/yarn
          key: yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run: yarn bootstrap
      - run: yarn test:ci
      - run: mkdir /tmp/workspace/ && mv node_modules /tmp/workspace
      - persist_to_workspace:
          root: /tmp/workspace
          paths: [ node_modules ]

  build-and-deploy:
    docker:
      - image: circleci/node:10
    steps:
      - checkout:
          post:
            - git fetch --all
      - attach_workspace:
          at: /tmp/workspace
      - run: mv /tmp/workspace/node_modules .
      - run: yarn build:ci
      - run:
          name: Setup git-related config
          command: |
            git config --global user.email "${GITHUB_EMAIL}"
            git config --global user.name "${GITHUB_USER}"
      - run: yarn new-version
      - run: yarn deploy:ci

workflows:
  version: 2
  continuous-integration:
    jobs:
      - test:
          filters:
            branches:
              ignore: [ release, master ]
  master:
    jobs:
      - test:
          filters:
            branches:
              only: master
      - build-and-deploy:
          requires:
            - test
          filters:
            branches:
              only: master
