version: 2.1
orbs:
  aws-cli: circleci/aws-cli@x.y
jobs:
  test:
    docker:
      - image: circleci/node:10
    steps:
      - checkout:
          post:
            - git fetch --all
      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-packages-v1-{{ .Branch }}-
            - yarn-packages-v1-
      - run: yarn install --freeze-lockfile
      - save_cache:
          paths:
            - ~/.cache/yarn
          key: yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run: yarn bootstrap
      - run: yarn test:ci
      - run: mv node_modules /tmp/workspace
      - persist_to_workspace:
          root: /tmp/workspace
          paths: [ node_modules ]

  deploy:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run: mv /tmp/workspace/node_modules .
      - run: yarn build:ci
      - run: yarn deploy:ci

workflows:
  version: 2
  continuous-integration:
    jobs:
      - build-and-test:
          filters:
            branches:
              ignore: [ release, master ]
  master:
    jobs:
      - build-and-test:
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - build-and-test
          filters:
            branches:
              only: master
